global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'raspberry_pi5'
    static_configs:
      - targets:
          - '192.168.11.109:8080'
    params:
      fallback_scrape_protocol: ['prometheus']
